
export const SET_CODE = 'SET_CODE'
export const GET_AVAX_PRICE = 'GET_AVAX_PRICE'
export const GET_TX_AVM = 'GET_TX_AVM'
export const SET_TX_HASH_EVM = 'SET_TX_HASH_EVM'
export const SET_VERIFY_CODE = 'SET_VERIFY_CODE'
export const SET_VALIDATOR_INFO = 'SET_VALIDATOR_INFO'
export const VERIFY_OWNER = 'VERIFY_OWNER'
export const GET_HEIGHT = 'GET_HEIGHT'
export const GET_SUPPLY = 'GET_SUPPLY'

export const SET_VALIDATORS = 'SET_VALIDATORS'
export const SET_VALIDATOR = 'SET_VALIDATOR'
export const SET_DELEGATORS = 'SET_DELEGATORS'
export const SET_DELEGATORS_COUNT = 'SET_DELEGATORS_COUNT'

export const SET_PENDING_DELEGATORS = 'SET_PENDING_DELEGATORS'
export const SET_PENDING_VALIDATORS = 'SET_PENDING_VALIDATORS'

export const GET_ASSETS_BY_BLOCKCHAINS = 'GET_ASSETS_BY_BLOCKCHAINS'
export const SET_ASSETS_COUNT = 'SET_ASSETS_COUNT'

export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS'
export const SET_NODE_CONNECTION_STATUS = 'SET_NODE_CONNECTION_STATUS'
export const GET_NODE_HEALTH = 'GET_NODE_HEALTH'

export const UPDATE_VALIDATOR = 'UPDATE_VALIDATOR'
