export const INIT_APP = 'INIT_APP'

export const GET_VALIDATORS = 'GET_VALIDATORS'
export const SET_VALIDATORS = 'SET_VALIDATORS'
export const SET_DEFAULT_VALIDATORS = 'SET_DEFAULT_VALIDATORS'
export const SET_DELEGATORS = 'SET_DELEGATORS'

export const GET_PENDING_VALIDATORS = 'GET_PENDING_VALIDATORS'
export const SET_PENDING_VALIDATORS = 'SET_PENDING_VALIDATORS'
export const SET_PENDING_DELEGATORS = 'SET_PENDING_DELEGATORS'

export const GET_BLOCKCHAINS = 'GET_BLOCKCHAINS'
export const SET_BLOCKCHAINS = 'SET_BLOCKCHAINS'
export const INIT_BLOCKCHAIN_VIEW = 'INIT_BLOCKCHAIN_VIEW'

export const GET_SUBNETS = 'GET_SUBNETS'
export const SET_SUBNETS = 'SET_SUBNETS'

export const SET_SUBNET_ID = 'SET_SUBNET_ID'

export const GET_ASSETS_BY_BLOCKCHAINS = 'GET_ASSETS_BY_BLOCKCHAINS'
export const SET_ASSETS_COUNT = 'SET_ASSETS_COUNT'

export const INIT_ENDPOINT = 'INIT_ENDPOINT'

export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS'
export const SET_NODE_CONNECTION_STATUS = 'SET_NODE_CONNECTION_STATUS'

export const GET_NODE_ID = 'GET_NODE_ID'
export const SET_NODE_ID = 'SET_NODE_ID'

export const GET_NODE_INFO = 'GET_NODE_INFO'
export const SET_NODE_INFO = 'SET_NODE_INFO'

export const GET_NODE_HEALTH = 'GET_NODE_HEALTH'
export const SET_NODE_HEALTH = 'SET_NODE_HEALTH'

export const SET_STAKED_AVA = 'SET_STAKED_AVA'
