export const INIT_APP = 'INIT_APP'

export const GET_VALIDATORS = 'GET_VALIDATORS'
export const INIT_VALIDATORS = 'INIT_VALIDATORS'
export const SET_VALIDATORS = 'SET_VALIDATORS'

export const GET_PENDING_VALIDATORS = 'GET_PENDING_VALIDATORS'
export const SET_PENDING_VALIDATORS = 'SET_PENDING_VALIDATORS'

export const GET_BLOCKCHAINS = 'GET_BLOCKCHAINS'
export const SET_BLOCKCHAINS = 'SET_BLOCKCHAINS'

export const GET_ASSETS_BY_BLOCKCHAINS = 'GET_ASSETS_BY_BLOCKCHAINS'
export const SET_ASSETS_BY_BLOCKCHAINS = 'SET_ASSETS_BY_BLOCKCHAINS'

export const SET_CURRENT_BLOCKCHAIN = 'SET_CURRENT_BLOCKCHAIN'
export const SET_ENDPOINT = 'SET_ENDPOINT'

export const GET_LAST_BLOCK = 'GET_LAST_BLOCK'
export const SET_BLOCK = 'SET_BLOCK'

export const GET_BLOCK_TIME = 'GET_BLOCK_TIME'
export const SET_BLOCK_TIME = 'SET_BLOCK_TIME'

export const GET_TX_FOR_24_HOURS = 'GET_TX_FOR_24_HOURS'
export const SET_TX_FOR_24_HOURS = 'SET_TX_FOR_24_HOURS'
export const SET_PREVIOUS_24_TXS = 'SET_PREVIOUS_24_TXS'

export const GET_TOTAL_TXS = 'GET_TOTAL_TXS'
export const SET_TOTAL_TXS = 'SET_TOTAL_TXS'
export const SET_PREVIOUS_TOTAL_TXS = 'SET_PREVIOUS_TOTAL_TXS'

export const GET_TXS_HISTORY = 'GET_TXS_HISTORY'
export const SET_TXS_HISTORY = 'SET_TXS_HISTORY'

export const SET_KEY_TXH = 'SET_KEY_TXH'
export const SET_ENDPOINTS_MEMORY = 'SET_ENDPOINTS_MEMORY'
export const REMOVE_ENDPOINTS_MEMORY = 'REMOVE_ENDPOINTS_MEMORY'

export const SET_LAST_BLOCK_TIME = 'SET_LAST_BLOCK_TIME'

export const GET_NODE_ID = 'GET_NODE_ID'
export const SET_NODE_ID = 'SET_NODE_ID'

export const GET_ACCOUNT = 'GET_ACCOUNT'
export const FUND_ACCOUNT = 'FUND_ACCOUNT'

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const ADD_VALIDATOR_TO_DEFAULT_SUBNET = 'ADD_VALIDATOR_TO_DEFAULT_SUBNET'

export const SIGN_TX = 'SIGN_TX'
export const CREATE_USER = 'CREATE_USER'
export const LIST_ACCOUNTS = 'LIST_ACCOUNTS'
