
export const SET_ENDPOINT = 'SET_ENDPOINT'

export const SET_ENDPOINTS_MEMORY = 'SET_ENDPOINTS_MEMORY'
export const REMOVE_ENDPOINTS_MEMORY = 'REMOVE_ENDPOINTS_MEMORY'

export const SET_CURRENT_SUBNET = 'SET_CURRENT_SUBNET'
export const SET_CURRENT_BLOCKCHAIN = 'SET_CURRENT_BLOCKCHAIN'
