export const UPDATE_UI = 'UPDATE_UI'

export const OPEN_ASSET_INFO = 'OPEN_ASSET_INFO'
export const CLOSE_ASSET_INFO = 'CLOSE_ASSET_INFO'

export const OPEN_NODE_HEALTH = 'OPEN_NODE_HEALTH'
export const CLOSE_NODE_HEALTH = 'CLOSE_NODE_HEALTH'

export const OPEN_NODE_INFO = 'OPEN_NODE_INFO'
export const CLOSE_NODE_INFO = 'CLOSE_NODE_INFO'

export const OPEN_ADD_IDENTIFICATION = 'OPEN_ADD_IDENTIFICATION'
export const CLOSE_ADD_IDENTIFICATION = 'CLOSE_ADD_IDENTIFICATION'
