export const UPDATE_UI = 'UPDATE_UI'

export const OPEN_P_CREATE = 'OPEN_P_CREATE'
export const CLOSE_P_CREATE = 'CLOSE_P_CREATE'

export const OPEN_SIGN_TX = 'OPEN_SIGN_TX'
export const CLOSE_SIGN_TX = 'CLOSE_SIGN_TX'

export const OPEN_CREATE_USER = 'OPEN_CREATE_USER'
export const CLOSE_CREATE_USER = 'CLOSE_CREATE_USER'

export const OPEN_ASSET_INFO = 'OPEN_ASSET_INFO'
export const CLOSE_ASSET_INFO = 'CLOSE_ASSET_INFO'

export const OPEN_NODE_HEALTH = 'OPEN_NODE_HEALTH'
export const CLOSE_NODE_HEALTH = 'CLOSE_NODE_HEALTH'

export const OPEN_SELECT_ACCOUNTS = 'OPEN_SELECT_ACCOUNTS'
export const CLOSE_SELECT_ACCOUNTS = 'CLOSE_SELECT_ACCOUNTS'

export const OPEN_ADD_IDENTIFICATION = 'OPEN_ADD_IDENTIFICATION'
export const CLOSE_ADD_IDENTIFICATION = 'CLOSE_ADD_IDENTIFICATION'

export const OPEN_ADD_VALIDATOR_DIALOG = 'OPEN_ADD_VALIDATOR_DIALOG'
export const CLOSE_ADD_VALIDATOR_DIALOG = 'CLOSE_ADD_VALIDATOR_DIALOG'

export const OPEN_DELEGATE_VALIDATOR_DIALOG = 'OPEN_DELEGATE_VALIDATOR_DIALOG'
export const CLOSE_DELEGATE_VALIDATOR_DIALOG = 'CLOSE_DELEGATE_VALIDATOR_DIALOG'
